name: Model training with Live Metrics in Studio
on:
  pull_request:
jobs:
  train:
    runs-on: ubuntu-latest
    name: Train model and report results
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch main branch
        run: git fetch --depth=1 origin main:main

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Train model
        env:
          STUDIO_ENDPOINT: ${{ secrets.STUDIO_ENDPOINT }}
          STUDIO_REPO_URL: ${{ secrets.STUDIO_REPO_URL }}
          STUDIO_TOKEN: ${{ secrets.STUDIO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DVCLIVE_LOGLEVEL: ${{ secrets.DVCLIVE_LOGLEVEL }}
        run: dvc repro

      - name: Update CML PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          dvc metrics diff main --show-md >> report.md
          npm exec -- cml comment create report.md
          npm exec -- cml pr --rebase "dvc.lock" "params.yaml" "dvclive"
